"""give public artifact links an expiry

`workflow_runs.public_access_token` is an unauthenticated bearer token: whoever
holds the URL can fetch that call's recording, both separated tracks and the
full transcript, with no session and no org membership. It never expired. There
was no revocation path either, so a token read out of an ordinary API response
kept working after the reader was demoted, removed from the organization, or
offboarded entirely.

Nullable with NO backfill, and that is the whole point of the design. NULL means
"never expires", which is exactly what every token minted before this column
existed keeps. Those URLs were handed to third parties in webhook payloads, in
the tuner and noveum integration payloads, and in exported CSVs customers have
already downloaded — and api/services/integrations/AGENTS.md instructs
integration authors to build durable URLs from the token. Backfilling a deadline
would silently revoke links the product promised would last.

New tokens get a deadline of PUBLIC_ARTIFACT_TOKEN_TTL_DAYS (default 7) from
mint. Written by hand rather than autogenerated: 181475b2a1a1 carries an
unreviewed autogenerate side effect on api_keys.key_hash, and running
--autogenerate here would sweep that up again.

Revision ID: b8d5e2f14c73
Revises: a4c17f39b8e2
Create Date: 2026-09-05 12:45:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8d5e2f14c73"
down_revision: Union[str, None] = "a4c17f39b8e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "workflow_runs",
        sa.Column(
            "public_access_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("workflow_runs", "public_access_token_expires_at")
